### ISSUE TITLE
No https :(

### ISSUE THREAD

**Issue by andrewmunro** [skybet/skybet.github.io#182]
How can we be proud industry leading engineers and not enforce https on our blog. 👎

**Comment by adamhepton** [comment]
We host on Github Pages, which doesn't support HTTPS for custom domains. 

https://github.com/isaacs/github/issues/156

**Comment by WheresAlice** [comment]
SSL support for this blog has been raised a few times, along with changing the subdomain, so I spent a bit of time this weekend looking at the options.  I've looked at and built proof of concepts for [Netlify](http://www.netlify.com) and AWS Cloudfront.

Netlify provides static hosting, and integrates with GitHub nicely.  A push to a given GitHub branch will build a new version of the site.  It's very simple to configure, even the addition of SSL (via LetsEncrypt).  I migrated two of my sites across to Netlify this weekend without any difficulty.  The free bronze version comes with all the features, but no support and is limited to a single user account.  The redirect to the new subdomain could be handled by having two separate sites, one doing nothing but sending http redirects to the new site.  However this would be a new provider that we would have to onboard.

AWS Cloudfront and AWS Certificate Manager is the other option that is possible.  This would mean leaving the site on GitHub pages, and using AWS Cloudfront as a caching proxy.  Redirects would be handled by creating a new S3 bucket for the old site which does nothing but redirect to the new site.  The SSL certificate would be provided by Amazon, and we would use SNI (non-SNI available for $600/month).  I'm a little unsure what we would need to do for cache invalidation, maybe a post-commit webhook to a Lambda function to invalidate the Cloudfront cache?  AWS is an existing provider which simplifies the onboarding process for this option.

I still don't feel like I know enough about how the AWS Cloudfront option to be confident in configuring it correctly.  However, we could configure the new subdomain without making any changes to the old one to begin with.

I suggest we follow up in Slack for any further discussion since a lot of this is process rather than technical.

**Comment by 8888888888888881** [comment]
@mitchellrj how can you be proud & industry leading if you leave trash reviews? hope you don't come near our apps that went live today. can't be very industry leading if you have to resort to dirty tactics. stay classy sky

**Comment by 8888888888888881** [comment]
@mitchellrj delete all of your trash google reviews

**Comment by quiltit5** [comment]
"The team also has a responsibility to improve monitoring & alerting, minimize downtime and reduce technical debt across the entire tribe." And resort to dirty tactics to promote their sub-par products

**Comment by cmbuckley** [comment]
Closing issue
